/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Is the process up?
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Is the process up *and* able to reach the database?
         *
         *     Runs one ``select 1`` through the session dependency. A database that does not
         *     answer is a 500 in the error envelope — which is what a probe for whatever keeps
         *     the process running wants to see rather than a timeout.
         */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorBody
         * @description The contents of an error: a machine-readable code and a human message.
         */
        ErrorBody: {
            /**
             * Code
             * @enum {string}
             */
            code: "not_found" | "conflict" | "invalid_request" | "unauthenticated" | "forbidden" | "internal_error";
            /** Fields */
            fields?: components["schemas"]["FieldError"][] | null;
            /** Message */
            message: string;
        };
        /**
         * ErrorResponse
         * @description The only error shape this API returns.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * FieldError
         * @description One field-level problem, for malformed requests.
         */
        FieldError: {
            /**
             * Location
             * @description Path to the offending field, e.g. ['body', 'title', 0]
             */
            location: string[];
            /** Message */
            message: string;
        };
        /**
         * HealthOkResponse
         * @description Response body for GET /health.
         */
        HealthOkResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * HealthReadyResponse
         * @description Response body for GET /health/ready.
         */
        HealthReadyResponse: {
            /**
             * Status
             * @constant
             */
            status: "ready";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description An opaque identifier for this request, minted by RequestIdMiddleware. Present on every response; correlates a client-side error report with a server-side log line. */
        "X-Request-ID": string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOkResponse"];
                };
            };
            /** @description Not signed in, or the session has ended */
            401: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in, but not allowed */
            403: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request, or a rule was broken */
            422: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unhandled server error */
            500: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReadyResponse"];
                };
            };
            /** @description Not signed in, or the session has ended */
            401: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in, but not allowed */
            403: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request, or a rule was broken */
            422: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unhandled server error */
            500: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
